version: '3.0'

services:
  db:
    container_name: stock_db_postgres
    image: postgres:14.1-alpine
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=stock_db
      - PG_DATA= /var/lib/postgresql/data
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local